{
  "$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
  "version": "2.1.0",
  "runs": [
    {
      "tool": {
        "driver": {
          "version": "1.0",
          "organization": "Lacework",
          "name": "lacework-vuln-scanner",
          "informationUri": "https://support.lacework.com/hc/en-us/articles/360035472393-Container-Vulnerability-Assessment-Overview",
          "rules": [
            {
              "id": "CVE-2021-36159",
              "helpUri": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-36159",
              "help": {
                "text": "",
                "markdown": "\nCVE-2021-36159 found in package apk-tools\n\n**Severity**: Critical\n**CVSSv3 Score**: 9.1\n**Image**: securethecloud/my-tweet-app-lacework:latest\n**Image layer hash**: sha256:691ab7bb77b9e4904bcd889db77af45e021b1ad1ab76ec97f70742fd823a1124\n**Image creation command**: ADD file:c5377eaa926bf412dd8d4a08b0a1f2399cfd708743533b0aa03b53d14cb4bb4e in / \n**Package Name**: apk-tools@2.10.6-r0\n\n#### Description\n\n\nMore details [here](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-36159).\n"
              },
              "properties": {
                "security-severity": "9.1",
                "CVSSv2": {
                  "PublishedDateTime": "2021-08-03T14:15Z",
                  "Score": 6.4,
                  "Vectors": "AV:N/AC:L/Au:N/C:P/I:N/A:P"
                },
                "CVSSv3": {
                  "ExploitabilityScore": 3.9,
                  "ImpactScore": 5.2,
                  "Score": 9.1,
                  "Vectors": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:H"
                }
              }
            },
            {
              "id": "CVE-2018-20225",
              "helpUri": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-20225",
              "help": {
                "text": "An issue was discovered in pip (all versions) because it installs the version with the highest version number, even if the user had intended to obtain a private package from a private index. This only affects use of the '--extra-index-url' option, and exploitation requires that the package does not already exist in the public index (and thus the attacker can put the package there with an arbitrary version number).",
                "markdown": "\nCVE-2018-20225 found in package pip\n\n**Severity**: Medium\n**CVSSv3 Score**: 7.8\n**Image**: securethecloud/my-tweet-app-lacework:latest\n**Image layer hash**: sha256:36978e00d4f2a969790ef724c9cf353cdb3afee25fe5cd40d20b1784fa285127\n**Image creation command**: RUN pip install --upgrade pip # buildkit\n**Package Name**: pip@20.3.4\n\n#### Description\nAn issue was discovered in pip (all versions) because it installs the version with the highest version number, even if the user had intended to obtain a private package from a private index. This only affects use of the '--extra-index-url' option, and exploitation requires that the package does not already exist in the public index (and thus the attacker can put the package there with an arbitrary version number).\n\nMore details [here](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-20225).\n"
              },
              "properties": {
                "security-severity": "7.8",
                "CVSSv2": {
                  "PublishedDateTime": "2020-05-08T18:15Z",
                  "Score": 6.8,
                  "Vectors": "AV:N/AC:M/Au:N/C:P/I:P/A:P"
                },
                "CVSSv3": {
                  "ExploitabilityScore": 1.8,
                  "ImpactScore": 5.9,
                  "Score": 7.8,
                  "Vectors": "CVSS:3.0/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H"
                }
              }
            },
            {
              "id": "CVE-2019-1010083",
              "helpUri": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-1010083",
              "help": {
                "text": "Denial of Service due to unexpected memory usage in the Pallets Project Flask",
                "markdown": "\nCVE-2019-1010083 found in package flask\n\n**Severity**: Medium\n**CVSSv3 Score**: 7.5\n**Image**: securethecloud/my-tweet-app-lacework:latest\n**Image layer hash**: sha256:634e0b74ac11e65ac0b65875edcf39a2e70cd459278cbc1e430488430a2a487e\n**Image creation command**: RUN pip install --no-cache-dir -r /usr/src/app/requirements.txt # buildkit\n**Package Name**: flask@0.12.3\n\n#### Description\nDenial of Service due to unexpected memory usage in the Pallets Project Flask\n\nMore details [here](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-1010083).\n"
              },
              "properties": {
                "security-severity": "7.5",
                "CVSSv2": {
                  "PublishedDateTime": "2019-07-17T14:15Z",
                  "Score": 5,
                  "Vectors": "AV:N/AC:L/Au:N/C:N/I:N/A:P"
                },
                "CVSSv3": {
                  "ExploitabilityScore": 3.9,
                  "ImpactScore": 3.6,
                  "Score": 7.5,
                  "Vectors": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
                }
              }
            }
          ]
        }
      },
      "results": [
        {
          "ruleId": "CVE-2021-36159",
          "message": {
            "text": "CVE-2021-36159"
          },
          "fingerprints": {
            "layer_hash": "sha256:691ab7bb77b9e4904bcd889db77af45e021b1ad1ab76ec97f70742fd823a1124"
          },
          "locations": [
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "Dockerfile"
                },
                "region": {
                  "startLine": 1,
                  "endLine": 1,
                  "startColumn": 1,
                  "endColumn": 5
                }
              }
            }
          ]
        },
        {
          "ruleId": "CVE-2018-20225",
          "message": {
            "text": "CVE-2018-20225"
          },
          "fingerprints": {
            "layer_hash": "sha256:36978e00d4f2a969790ef724c9cf353cdb3afee25fe5cd40d20b1784fa285127"
          },
          "locations": [
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "Dockerfile"
                },
                "region": {
                  "startLine": 7,
                  "endLine": 7,
                  "startColumn": 1,
                  "endColumn": 4
                }
              }
            }
          ]
        },
        {
          "ruleId": "CVE-2019-1010083",
          "message": {
            "text": "CVE-2019-1010083"
          },
          "fingerprints": {
            "layer_hash": "sha256:634e0b74ac11e65ac0b65875edcf39a2e70cd459278cbc1e430488430a2a487e"
          },
          "locations": [
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "Dockerfile"
                },
                "region": {
                  "startLine": 11,
                  "endLine": 11,
                  "startColumn": 1,
                  "endColumn": 4
                }
              }
            }
          ]
        }
      ]
    }
  ]
}